# Generated by Django 4.2.6 on 2023-10-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apelldo', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=20)),
                ('Numero_cedula', models.IntegerField(max_length=12)),
            ],
        ),
    ]
