# Generated by Django 4.2.6 on 2023-10-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_numero_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Numero_cedula',
        ),
    ]
