# Generated by Django 4.2.6 on 2023-10-14 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_numero_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Especialidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero_cedula', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('contacto_emergencia', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='Personal',
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Metodo_pago', models.CharField(choices=[('e', 'EFECTIVO'), ('TC', 'Tarjeta de credito'), ('TD', 'Tarjeta de debito'), ('pse', 'Pse'), ('c', 'Cheque'), ('cb', 'Consignacion bancaria')], max_length=20)),
                ('Interno_mesualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.interno')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_medicamento', models.CharField(max_length=30)),
                ('recomendaciones', models.CharField(max_length=150)),
                ('Interno_medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.interno')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Sangre', models.CharField(choices=[('O+', 'O POSITIVO'), ('O-', 'O NEGATIVO'), ('A+', 'A POSITIVO'), ('A-', 'A NEGATIVO'), ('AB+', 'AB POSITIVO'), ('AB-', 'AB NEGATIVO'), ('B+', 'B POSITIVO'), ('B-', 'B NEGATIVO')], max_length=3)),
                ('Contacto_Emergencia', models.IntegerField()),
                ('Enfermedades', models.CharField(max_length=255)),
                ('Cirugias', models.CharField(max_length=255)),
                ('Fecha_cirugias', models.DateField()),
                ('Interno_Historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.interno')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_habitacion', models.IntegerField()),
                ('Interno_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.interno')),
            ],
        ),
    ]
